# Generated by Django 2.2 on 2019-12-04 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beautyapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addstaff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('mobileno', models.CharField(max_length=12)),
                ('services', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='beautyapp.Services')),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gname', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=50)),
                ('time_in', models.TimeField()),
                ('time_out', models.TimeField()),
                ('total_time', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('payment', models.CharField(max_length=100)),
                ('comments', models.CharField(default='NA', max_length=500)),
                ('services', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='beautyapp.Services')),
                ('treatment_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Addstaff')),
            ],
        ),
    ]
